<?php
// function customety_form_alter(&$form, &$form_state, $form_id) {
//   //echo $form_id;
//   $uroles = user_roles();
//   if($form_id == "article_node_form"){
//     //echo "string";
//     kpr($form);
//
//     }
//   }

/**
 * Implements hook_ENTITY_TYPE_access().
 */
//function customety_paragraph_access(EntityInterface $entity, $operation, AccountInterface $account) {

  // if ($operation !== 'update') {
  //   return AccessResult::neutral();
  // }
  //
  //
  // if ($entity->getOwnerId() !== $account->id()) {
  //   return AccessResult::forbidden();
  // }
  //
  // return AccessResult::neutral();
//}

// function customety_node_view($node, $view_mode, $langcode) {
//   if($node->type == "article"){
//     $delta = 0;
//     //$max_delta = $node->field_paragraph_ref['und']['#max_delta']);
//
//     while ($delta <= 1) {
//       $prgid = $node->field_paragraph_ref['und'][$delta]['value'];
//       $entities = entity_load('paragraphs_item', array($prgid));
//       if (!array_key_exists($entities[$prgid]->field_role_field['und'][0]['value'], $GLOBALS['user']->roles)) {
//         kpr($node->field_paragraph_ref['und'][$delta]);
//       }
//       $delta++;
//     }
//
//     // if (!array_key_exists($form['field_paragraph_ref'][LANGUAGE_NONE][$delta]['field_role_field']['und']['#default_value'][0], $GLOBALS['user']->roles)) {
//     //     $form['field_paragraph_ref'][LANGUAGE_NONE][$delta]['#access'] = FALSE;
//     // }
//   }
//
//     // Code here.
//   }

// function customety_field_widget_form_alter(&$element, &$form_state, &$context) {
//   if(isset($element['#entity_type'])){
//     if($element['#entity_type']=='paragraphs_item'){
//       kpr($context);
//       //$default_value = _optionss_storage_to_form($items, $options, $value_key, $properties);
//       $element['field_sel'] = array(
//             '#type' => 'select',
//             '#title' => t('Role selection'),
//             "#empty_option"=>t('- Select -'),
//             '#options' => array(
//               "1"=>"hello",
//               "2"=>"internal",
//             ),
//             '#value' => isset($context['delta']) ? $context['delta'] : '',
//             '#default_value' => "1",
//             //'#value' => isset($context['delta']) ? $context['delta'] : '',
//             '#element_validate' => array('myelement_validate'),
//       );
//
//
//     //  kpr($form_state);
//       // echo '<pre>';
//       // print_r($form_state);die;
//     }
//   }
// }


function customety_preprocess_entity(&$variables) {

  //  echo $variables['entity_type'];
  $function = __FUNCTION__ . '_' . $variables['entity_type'];
   if (function_exists($function)) {
     $function($variables);
   }
}

function customety_preprocess_entity_paragraphs_item(&$variables) {
  if(!user_has_role(3)){
    if (!array_key_exists($variables['custom_role_field'][0]['value'], $GLOBALS['user']->roles)) {
        $variables['classes_array'][]="hiding-paragraph";
        // unset($variables);
        unset($variables['content']);
    }
    $variables['content']['custom_role_field']['#access']=false;
  }
}

function customety_form_alter(&$form, &$form_state, $form_id) {
  if(!user_has_role(3)){
    if($form_id == 'article_node_form') {
    $delta = 0;
    //kpr($form);
    $max_delta = $form['field_paragraph_ref'][LANGUAGE_NONE]['#max_delta'];
        while ($delta <= $max_delta) {
          if (!array_key_exists($form['field_paragraph_ref'][LANGUAGE_NONE][$delta]['custom_role_field']['und']['#default_value'][0], $GLOBALS['user']->roles)) {
              $form['field_paragraph_ref'][LANGUAGE_NONE][$delta]['#access'] = FALSE;
          }
          //$form['field_paragraph_ref'][LANGUAGE_NONE][$delta]['custom_role_field']['#access'] = FALSE;
          $delta++;
        }
     }
  }
}

 ?>
